node('master'){
    stage('Clean'){
        deleteDir()
        sh 'ls -la'
    }
    
    stage('Fetch') {
        checkout scm
    }
        
    stage('Docker Build') {
        sh 'docker build -t marceloweb/twitter:$BUILD_NUMBER .'
    }
    
    stage('Docker Ship') {
        sh 'docker push marceloweb/twitter:$BUILD_NUMBER'
    }
}